#cloud-config
password: fed0ra
chpasswd: { expire: false }

users:
  - default
  - name: root
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUh0vt15Wgc7CQvgbh7tcisOeAY1odTzsIF3dXsB8aqn+hRmUy2l0C/ELgiETGHtdnkCyVEi8pi6G+kGUFAfJ6HZWURf3eifsg0CrWH1y2A9CRpn3Z5F0jM17jUiBv5CrqPv63CBa+DQN54/mFUcOIN+EspqkHkQOhsP23s1YGLJ04DdX4pfe0nyo5CjAAEXnKn6dNWtGuqRunIdOskspdeq7dTYs/wChyEyiSQnzaOaHs7zbJ/ivdFjDPfMpFhIfrFAZY+q90Ut4LR/9IQL8ZW6OKEeoVftXpGIO6W9oVkMTojBHEl5c64FOgYsFg3wFfemMQ5LZcO/Pd8SkYYOKz Thierry.Parmentelat"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1Gulhus09dvuykqIng39+P93FL+MhadI/9NhNyIkHDeKSSDks4+PTz4N+js5rT7Qax6SAe/+EbVn17bcNPexgqle77BvroLkbgxINpDshGDkQ2dmP6q7LYyQwXT2vMOhnZWzr30xVqMpZS31UQBrMvWrbsXVcTu55W0iPkNei1ap/BIHvOXdGKMeKOhg/dgsR+driZ/+6x70v/yDjn4b/t29xp7O8/nOKYNUHSx34IbIijV5bZGLrNR9X9JBVyIQmd/S+jPKGmMjOZ91ockytRG1o4tqwv7BDRh+Ar96YDd5upVP94uVA09R7vl90g1sST7oTMSU4Ssq674J8l83bQ== root@build.one-lab.org"

chpasswd:
  list:
    - root:r00t
