#cloud-config
#password: fed0ra
#chpasswd: { expire: false }

hostname: {{vnode}}
fqdn: {{vnode}}.pl.sophia.inria.fr
ssh_pwauth: no

users:
#  - default
  - name: root
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUh0vt15Wgc7CQvgbh7tcisOeAY1odTzsIF3dXsB8aqn+hRmUy2l0C/ELgiETGHtdnkCyVEi8pi6G+kGUFAfJ6HZWURf3eifsg0CrWH1y2A9CRpn3Z5F0jM17jUiBv5CrqPv63CBa+DQN54/mFUcOIN+EspqkHkQOhsP23s1YGLJ04DdX4pfe0nyo5CjAAEXnKn6dNWtGuqRunIdOskspdeq7dTYs/wChyEyiSQnzaOaHs7zbJ/ivdFjDPfMpFhIfrFAZY+q90Ut4LR/9IQL8ZW6OKEeoVftXpGIO6W9oVkMTojBHEl5c64FOgYsFg3wFfemMQ5LZcO/Pd8SkYYOKz Thierry.Parmentelat"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1Gulhus09dvuykqIng39+P93FL+MhadI/9NhNyIkHDeKSSDks4+PTz4N+js5rT7Qax6SAe/+EbVn17bcNPexgqle77BvroLkbgxINpDshGDkQ2dmP6q7LYyQwXT2vMOhnZWzr30xVqMpZS31UQBrMvWrbsXVcTu55W0iPkNei1ap/BIHvOXdGKMeKOhg/dgsR+driZ/+6x70v/yDjn4b/t29xp7O8/nOKYNUHSx34IbIijV5bZGLrNR9X9JBVyIQmd/S+jPKGmMjOZ91ockytRG1o4tqwv7BDRh+Ar96YDd5upVP94uVA09R7vl90g1sST7oTMSU4Ssq674J8l83bQ== root@build.one-lab.org"
  - name: kuber
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUh0vt15Wgc7CQvgbh7tcisOeAY1odTzsIF3dXsB8aqn+hRmUy2l0C/ELgiETGHtdnkCyVEi8pi6G+kGUFAfJ6HZWURf3eifsg0CrWH1y2A9CRpn3Z5F0jM17jUiBv5CrqPv63CBa+DQN54/mFUcOIN+EspqkHkQOhsP23s1YGLJ04DdX4pfe0nyo5CjAAEXnKn6dNWtGuqRunIdOskspdeq7dTYs/wChyEyiSQnzaOaHs7zbJ/ivdFjDPfMpFhIfrFAZY+q90Ut4LR/9IQL8ZW6OKEeoVftXpGIO6W9oVkMTojBHEl5c64FOgYsFg3wFfemMQ5LZcO/Pd8SkYYOKz Thierry.Parmentelat"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1Gulhus09dvuykqIng39+P93FL+MhadI/9NhNyIkHDeKSSDks4+PTz4N+js5rT7Qax6SAe/+EbVn17bcNPexgqle77BvroLkbgxINpDshGDkQ2dmP6q7LYyQwXT2vMOhnZWzr30xVqMpZS31UQBrMvWrbsXVcTu55W0iPkNei1ap/BIHvOXdGKMeKOhg/dgsR+driZ/+6x70v/yDjn4b/t29xp7O8/nOKYNUHSx34IbIijV5bZGLrNR9X9JBVyIQmd/S+jPKGmMjOZ91ockytRG1o4tqwv7BDRh+Ar96YDd5upVP94uVA09R7vl90g1sST7oTMSU4Ssq674J8l83bQ== root@build.one-lab.org"

chpasswd:
  list:
    - root:r00t
    - kuber:kuber++
  expire: no

ssh_keys:
  rsa_private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEA1+o2lhchiNVgBKTdWJ95Y7+TvOd7kDx0NDKXMklctfAp/BfdgVD7
    AKKwLU+AsZyJ7vxNnIm8TMXxRsgXXArvRkmh7XmPy4WbPn+g0GPiFxNH7/ydZwK5JyhFjK
    u+y69S6YPQO1kBF/sQDdb8kYFNO1wWbnf3jDwiRX46jstWOMjfXlSoPe75idu2wi3OYF5f
    k5e+Z7XmkK4ZD6vB8VxiKyHh0w6Jf1YjeWi9LibTNswKZ8idGzGtw2UfkbBLyqzzOU3haW
    GCAv62HI0vy9SdSVCk9z3VeIojulpsSQOPbupSfgxwp2jU9fcqDAqGSQgitPdRFr9yTE22
    c4MobmZvi0xhm/JwcYQfH/48AVpPMhEG5ojlJSDOzzKPSej6vBvKfEcj74PvRhIF9WzlHa
    Frx8+aC0ZVRtcjm8KZjETA9G7MHWlZe2Lhs0S+BvyF7GeZkTRZfEllMGaJoNF4czQELp5/
    +2/Zt6/0GOIlkqSh7m4rvaDX4OvgJYkvmgwaMolNAAAFmCMSi1IjEotSAAAAB3NzaC1yc2
    EAAAGBANfqNpYXIYjVYASk3VifeWO/k7zne5A8dDQylzJJXLXwKfwX3YFQ+wCisC1PgLGc
    ie78TZyJvEzF8UbIF1wK70ZJoe15j8uFmz5/oNBj4hcTR+/8nWcCuScoRYyrvsuvUumD0D
    tZARf7EA3W/JGBTTtcFm5394w8IkV+Oo7LVjjI315UqD3u+YnbtsItzmBeX5OXvme15pCu
    GQ+rwfFcYish4dMOiX9WI3lovS4m0zbMCmfInRsxrcNlH5GwS8qs8zlN4WlhggL+thyNL8
    vUnUlQpPc91XiKI7pabEkDj27qUn4McKdo1PX3KgwKhkkIIrT3URa/ckxNtnODKG5mb4tM
    YZvycHGEHx/+PAFaTzIRBuaI5SUgzs8yj0no+rwbynxHI++D70YSBfVs5R2ha8fPmgtGVU
    bXI5vCmYxEwPRuzB1pWXti4bNEvgb8hexnmZE0WXxJZTBmiaDReHM0BC6ef/tv2bev9Bji
    JZKkoe5uK72g1+Dr4CWJL5oMGjKJTQAAAAMBAAEAAAGAOhU5hfrG/KZZ5CXtnY+Y+ippNe
    IXrV916yzI27A8jn0C7lwFLGp6e1tIhYfjmOQBfxbEUh4DV6vQEjh1gD84yvG368hN1HQm
    pRN0UVrtUUPQkFCmjzV+VXhR7VuuQeDyLvtUowJ4dtkFIpP48bOU8Sj+p80B/OmYVpV0b0
    Fn+nKfFCM19yM4YcuHSIlGAUqh73Rctk2KrtUGzN5pl+JATlYZB8vbVTP46wowCiBLpWwS
    SIUBLnWYxv2HFowUd3s6nD/fOXLS2zpH5qamHTBCfvkaEayx50AgdcoZXkpuOzrfqIeTaj
    mr/0z6iBQdvVbFQL8zjTb3LGeIB1aifwnyKUFr/9NjLT2c0Y5ttoFmlm6mScvGwZdOzrAL
    LqkYD2xAjhRCe0kV5AzagBvYdE4PTjQ/4mO/0czNwWf+1KyEB+WKaP+YQqqwKb68n4m/5C
    F/aDh32ClnxrTDOFbpbFk6J0SlcND+0A3Ehmdn6+eBoMx3WfepyPWal3Vq9RsxTWHBAAAA
    wQDPkaNSAoejBDqSIxXQlcHHBNqv0qGkU52A7L45Xzphxr3RwnQLrRj0HWjnZjIheED0+X
    Pew2BbWFMna6htBAke7+P+xpjO61W0iGVo5bQoNVQ3GfUlc5ocW6Xz3oaa4R6upwN53gPZ
    1fur3/FoC9u9SaXPh082rvfcIVNMPpZzlTGh7KQWTC9gyZBgcQMw4XSN7OT9XVIHuoLc0Y
    TdLfSFiiVYF4NdKd6UFXEfF2+WJWAutJ/Nl5fSVK9FWKwtQ5IAAADBAPerfKDktBPev3w1
    sCzHGmqR1W7fNI4OkD5+tOv3bGb9R9TVMIQkKWPUK0dT2niZPr7lJoyS36vuWypFggwYN4
    UYg5jeasKZ6zk+aGqnUYMQUshWcYUkzmj95+nnwj8amUksBS/IBnzYS84ILTdVcviWtfFt
    DtYCYHbW0M/CKbXYYWlVkvJ/Du6zK5RbEvnHpPEnRmW1OP/pS8AZt17G0/J70KqTUyhq76
    8DowOJCET0/U7TW3rF237dTE5Fd0NtCQAAAMEA3y1Obl8PxSwsZcHdt8L3bKXDCJr7lYHS
    /6PaUttW9kCycR5zMgjXd6MDG/k8l/CybG/oUb047TwfgZm+HZZPrO903TAmFZgDw0WLND
    QfSXS+GgsQQSJcBmK+kaHs4tG9JTZaUcofXg1JKzjMsOlEDUpJGQMInj4o9dk5JVvtLAlM
    103tW/pnzVN5518n4KDGgvQRp/EikzjhGoIeQV+IG2TrAPZR3QFIxkeqCUsW+KOM9NBkx4
    ERyph0AHC53k8lAAAAG3Jvb3RAZnItZnItNTc0ZS5lZGdlLW5ldC5pbwECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----

  rsa_public: >
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX6jaWFyGI1WAEpN1Yn3ljv5O853uQPHQ0MpcySVy18Cn8F92BUPsAorAtT4CxnInu/E2cibxMxfFGyBdcCu9GSaHteY/LhZs+f6DQY+IXE0fv/J1nArknKEWMq77Lr1Lpg9A7WQEX+xAN1vyRgU07XBZud/eMPCJFfjqOy1Y4yN9eVKg97vmJ27bCLc5gXl+Tl75nteaQrhkPq8HxXGIrIeHTDol/ViN5aL0uJtM2zApnyJ0bMa3DZR+RsEvKrPM5TeFpYYIC/rYcjS/L1J1JUKT3PdV4iiO6WmxJA49u6lJ+DHCnaNT19yoMCoZJCCK091EWv3JMTbZzgyhuZm+LTGGb8nBxhB8f/jwBWk8yEQbmiOUlIM7PMo9J6Pq8G8p8RyPvg+9GEgX1bOUdoWvHz5oLRlVG1yObwpmMRMD0bswdaVl7YuGzRL4G/IXsZ5mRNFl8SWUwZomg0XhzNAQunn/7b9m3r/QY4iWSpKHubiu9oNfg6+AliS+aDBoyiU0= root@fr-fr-574e.edge-net.io
